name:                blnd-on-tezos
version:             0.1.0.0
github:              "https://github.com/StakerDAO/blnd-on-tezos"
author:              Serokell <hi@serokell.io>
copyright:           "2020 Author name here"
git:                 git@github.com:StakerDAO/blnd-on-tezos.git

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Please see the README on GitHub at <https://github.com/StakerDAO/blnd-on-tezos#readme>

verbatim:
  cabal-version: 2.2

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NegativeLiterals
- NoImplicitPrelude
- NumDecimals
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- UndecidableSuperClasses
- ViewPatterns
- NoApplicativeDo
- RebindableSyntax

dependencies:
- base-noprelude >= 4.9 && < 5
- bytestring
- morley-prelude
- universum

ghc-options:
- -optP-Wno-nonportable-include-path
- -Wall
- -fno-warn-orphans
- -Widentities
- -Wincomplete-record-updates
- -Werror

library:
  source-dirs: src
  build-tools:
  - autoexporter
  dependencies:
  - indigo
  - fmt
  - lorentz
  - morley
  - morley-ledgers
  - text

executables:
  blnd-on-tezos:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blnd-on-tezos

tests:
  blnd-on-tezos-test:
    main:        Main.hs
    source-dirs: test
    build-tools: tasty-discover:tasty-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blnd-on-tezos
    - tasty
    - hspec
    - QuickCheck
    - cleveland
    - lorentz
    - morley
    - hedgehog
    - tasty-hedgehog
    - containers
    - fmt
