resolver: lts-16.5

packages:
- .

extra-deps:
# required by loot-log
- componentm-0.0.0.2
- teardown-0.5.0.1

# Lootbox (prelude, logging, configuration)
- git: https://github.com/serokell/lootbox.git
  commit: 18ced0d493348b4d6bae8517dff7ee6de6e0c9d9
  # nix-sha256: 0y8gfdivjxx0jj8g651k5nzzwjg8mj9qw2s3v75vbpr8p008ymnr
  subdirs:
    - code/base
    - code/config
    - code/log
    - code/prelude

# morley
- git: https://gitlab.com/morley-framework/morley.git
  commit: 48cc2608392b387941817a7b5126c0f7b289626b
  subdirs:
    - code/morley
    - code/morley-prelude
    - code/lorentz
    - code/indigo
    - code/cleveland
    - code/morley-client

# morley-ledgers
- git: https://gitlab.com/morley-framework/morley-ledgers.git
  commit: 6d24cac25941b55cb7e45d859cd8cb01f2415c92
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test

- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
  # nix-sha256: 0r1zqa559gaxavsd8zynlpa2c5hi2qc20n8s4bhcdaw36hasg3kr

# required for morley
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- show-type-0.1.1
- named-0.3.0.1
- vinyl-0.12.1
- cryptonite-0.27
- tasty-hunit-compat-0.2
